FROM graalvm-native-image:20.0.0-java11 as stage0
ARG KRB_OPERATOR_JAR_PATH
COPY / /root
WORKDIR /root
RUN native-image --static -jar ${KRB_OPERATOR_JAR_PATH} kerberos-operator
RUN ["mkdir", "-p", "/opt/docker/resources"]
RUN ["cp", "/root/kerberos-operator", "/opt/docker/kerberos-operator"]
RUN ["cp", "-R", "/root/src/main/resources",  "/opt/docker"]
USER root
RUN ["chmod", "-R", "u=rX,g=rX", "/opt/docker"]
RUN ["chmod", "u+x,g+x", "/opt/docker/kerberos-operator"]

FROM alpine:3.11.3
USER root
RUN id -u demiourgos728 1>/dev/null 2>&1 || (( getent group 0 1>/dev/null 2>&1 || ( type groupadd 1>/dev/null 2>&1 && groupadd -g 0 root || addgroup -g 0 -S root )) && ( type useradd 1>/dev/null 2>&1 && useradd --system --create-home --uid 1001 --gid 0 demiourgos728 || adduser -S -u 1001 -G root demiourgos728 ))
WORKDIR /opt/docker
COPY --from=stage0 --chown=demiourgos728:root /opt/docker /opt/docker
USER 1001:0
ENTRYPOINT ["/opt/docker/kerberos-operator"]
CMD []