FROM oracle/graalvm-ce:20.0.0-java11 as stage0
ARG KRB_OPERATOR_JAR_PATH
COPY / /root
RUN gu install native-image
WORKDIR /root
RUN curl -L -o musl.tar.gz https://github.com/gradinac/musl-bundle-example/releases/download/v1.0/musl.tar.gz && \
    tar -xvzf musl.tar.gz || ls
RUN /opt/graalvm-ce-java11-20.0.0/lib/svm/bin/native-image --static -jar ${KRB_OPERATOR_JAR_PATH} kerberos-operator
RUN ["mkdir", "-p", "/opt/docker/resources"]
RUN ["cp", "/root/kerberos-operator", "/opt/docker/kerberos-operator"]
RUN ["cp", "-R", "/root/src/main/resources",  "/opt/docker"]
USER root
RUN ["chmod", "-R", "u=rX,g=rX", "/opt/docker"]
RUN ["chmod", "u+x,g+x", "/opt/docker/kerberos-operator"]

#FROM alpine:3.11.3
FROM ubuntu
#USER root
#RUN id -u demiourgos728 1>/dev/null 2>&1 || (( getent group 0 1>/dev/null 2>&1 || ( type groupadd 1>/dev/null 2>&1 && groupadd -g 0 root || addgroup -g 0 -S root )) && ( type useradd 1>/dev/null 2>&1 && useradd --system --create-home --uid 1001 --gid 0 demiourgos728 || adduser -S -u 1001 -G root demiourgos728 ))
WORKDIR /opt/docker
#COPY --from=stage0 --chown=demiourgos728:root /opt/docker /opt/docker
COPY --from=stage0 /opt/docker /opt/docker
#USER 1001:0
ENTRYPOINT ["/opt/docker/kerberos-operator"]
CMD []