# for creating these resources it requires the user to be logged in as system admin
apiVersion: v1
kind: ServiceAccount
metadata:
  name: krb-operator
  namespace: {{NAMESPACE}}
  labels:
    app: krb-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: krb-operator
  labels:
    app: krb-operator
subjects:
  - kind: ServiceAccount
    name: krb-operator
    namespace: {{NAMESPACE}}
roleRef:
  kind: ClusterRole
  name: krb-operator
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: krb-operator
rules:
  # "" - the core API group
  - apiGroups: ["", "authorization.k8s.io", "extensions"]
    resources: ["pods", "services", "configmaps", "secrets", "pods/exec", "deploymentconfigs"]
    verbs: ["get", "watch", "list", "create", "update", "delete"]
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "watch", "list"]
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["get", "watch", "list", "create"]
  - apiGroups: ["krb-operator.novakov-alexey.github.io"]
    resources: ["krbservers", "krbservers/status", "principalss", "principalss/status"]
    verbs: ["watch", "list", "update"]
  # for OpenShift
  - apiGroups: ["apps.openshift.io"]
    resources: ["deploymentconfigs"]
    verbs: ["get", "create", "list", "delete"]
  # for kubernetes, i.e. not for OpenShift
  - apiGroups: ["", "apps", "extensions"]
    resources: ["deployments"]
    verbs: ["get", "create", "list", "delete"]